const taskBank = [
    "Share on your local neighborhood FB group or NextDoor group one local candidate you're voting for and why.",
    "Encourage your social media audience to fill out the Census. (Language from Population Reference Bureau)",
    "Sign up to write letters to likely voters with @votefwd",
    "Text 5 people and make sure they have a voting plan.",
    "For parents of young children: ask your daycare what the Election day plans are so teachers can vote.",
    "Sign up to phone bank! Your local county democratic party is likely phone banking for close races at the state level!",
    "If you're not in a swing state, adopt a state! ",
    "Commit to volunteer during the last weekends before the election.",
    "Become a poll watcher for election day.",
    "The Great Slate is an effort to help secure a Senate majority in the 2020 elections by ",
    "supporting five rural Democratic House campaigns in battleground states.",
    "Thank a reporter on social media. (Tag them in your post.) They are doing hard work and have had a very hard year.",
    "Donate to a local news organization that is pounding the pavement and breaking stories.",
    "Call your local senior center and see if they need drivers to take people to the polls.",
    "Calcuate your time on social media and use that time the next day to write letters!",
    "Take a day off! ",
    "Donate your tech skills for a campaign.",
    "Volunteer to translate material for a local candidate.",
    "Check your voter registration status.",
    "Make your voting plan.",
    "Give them money. The Pinboard slate is here.",
    "Look at this spreadsheet of flippable seats and commit to donating to one of them.",
    "Put the Election Protection Hotline number in your phone: 1-866-OUR-VOTE (ACLU tweet)",
    "Donate to the Southern Coalition for Social Justice. ",
    "State and district courts are critically important right now. Please educate ",
    "yourselves on the candidates and vote in every race on the ballot. (NC Voter Guide here.)",
    "Write postcards.",
    "Text canvass voters!",
    "Sign up for 2020 Victory National Text Team Training!",
    "Give your brain a break and stop doomscrolling.",
    "Resource your local anti-racism movement.",
    "Plan for self-care and community care in November and the years to come.",
    "Fund voter protection and registration for people of color. Some choices: @votolatino, @BlackVotersMtr, @PIVOTorg! ",
    "If your state has a witness requirement, you can offer to witness other people's ballots in safe ways. This is a really good way to help absentee voters who may live alone!",
    "Host a virtual textbanking event!",
    "Protect the Vote is looking for folks to staff voter protection hotlines, volunteer as poll observers, and sign up to be election workers during Early Vote  and on Election Day.",
];

export default taskBank;
